export const MODELS = [
  // Deep Learning › Feedforward
  {key:'mlp',icon:'⬡',label:'MLP',name:'Multi-Layer Perceptron',cat:'Deep Learning',sub:'Feedforward',fw:['pytorch','tensorflow','jax','sklearn'],params:'3.2K',year:1986,
   desc:'Universal approximator via stacked affine+activation layers. Learns hierarchical non-linear feature representations through gradient descent.',
   layers:[{n:'Input',t:'input',u:4,desc:'Raw feature vector'},{n:'Dense 128',t:'dense',u:8,desc:'First hidden layer'},{n:'BatchNorm',t:'norm',u:8,desc:'Normalize activations'},{n:'Dropout 0.3',t:'norm',u:7,desc:'Regularization'},{n:'Dense 64',t:'dense',u:6,desc:'Second hidden layer'},{n:'Dense 32',t:'dense',u:5,desc:'Third hidden layer'},{n:'Softmax',t:'output',u:3,desc:'Class probabilities'}],
   use_cases:['Tabular classification','Regression','Feature learning'],pros:['Universal approximator','Flexible'],cons:['No spatial/sequential inductive bias','Needs feature engineering']},
  
  // Deep Learning › Vision
  {key:'cnn',icon:'◈',label:'CNN',name:'Convolutional Neural Net',cat:'Deep Learning',sub:'Vision',fw:['pytorch','tensorflow','onnx'],params:'122K',year:1989,
   desc:'Hierarchical feature extraction with weight-shared convolutional filters. Achieves translation invariance via pooling operations.',
   layers:[{n:'Input(3)',t:'input',u:3,desc:'RGB image channels'},{n:'Conv2D-32',t:'conv',u:6,desc:'3×3 filters, detect edges'},{n:'BatchNorm',t:'norm',u:6,desc:'Normalize feature maps'},{n:'MaxPool(2)',t:'pool',u:5,desc:'2× spatial downsampling'},{n:'Conv2D-64',t:'conv',u:5,desc:'3×3 filters, detect patterns'},{n:'MaxPool(2)',t:'pool',u:4,desc:'2× spatial downsampling'},{n:'Flatten',t:'flatten',u:4,desc:'Reshape to 1D'},{n:'Dense 128',t:'dense',u:5,desc:'Classification head'},{n:'Output',t:'output',u:3,desc:'Class scores'}],
   use_cases:['Image classification','Object detection','Segmentation'],pros:['Spatial feature learning','Weight sharing'],cons:['Data hungry','Computationally heavy']},
  {key:'resnet',icon:'⟲',label:'ResNet-50',name:'Residual Network',cat:'Deep Learning',sub:'Vision',fw:['pytorch','tensorflow','onnx'],params:'25.6M',year:2015,
   desc:'Skip connections F(x)+x allow stable gradient flow in extremely deep networks by learning residual mappings rather than unreferenced functions.',
   layers:[{n:'Stem Conv',t:'conv',u:4,desc:'7×7 conv, stride 2'},{n:'Pool',t:'pool',u:4,desc:'3×3 max pool'},{n:'Stage1 ×3',t:'residual',u:6,desc:'Bottleneck blocks 64ch'},{n:'Stage2 ×4',t:'residual',u:7,desc:'Bottleneck blocks 128ch'},{n:'Stage3 ×6',t:'residual',u:7,desc:'Bottleneck blocks 256ch'},{n:'Stage4 ×3',t:'residual',u:6,desc:'Bottleneck blocks 512ch'},{n:'GAP',t:'pool',u:4,desc:'Global average pool'},{n:'FC 1000',t:'output',u:3,desc:'ImageNet classes'}],
   use_cases:['ImageNet classification','Transfer learning','Backbone'],pros:['Very deep without degradation','Strong transfer'],cons:['Memory intensive','Many params']},
  {key:'vgg16',icon:'▣',label:'VGG-16',name:'Very Deep ConvNet',cat:'Deep Learning',sub:'Vision',fw:['pytorch','tensorflow','onnx'],params:'138M',year:2014,
   desc:'16-layer architecture of uniform 3×3 convolutions. Demonstrated that depth with small kernels is key for strong visual representations.',
   layers:[{n:'Block1 ×2',t:'conv',u:5,desc:'64 filters, 3×3'},{n:'MaxPool',t:'pool',u:4,desc:'2× downsample'},{n:'Block2 ×2',t:'conv',u:5,desc:'128 filters, 3×3'},{n:'MaxPool',t:'pool',u:4,desc:'2× downsample'},{n:'Block3 ×3',t:'conv',u:6,desc:'256 filters, 3×3'},{n:'Block4 ×3',t:'conv',u:6,desc:'512 filters, 3×3'},{n:'FC-4096',t:'dense',u:7,desc:'Fully connected'},{n:'FC-4096',t:'dense',u:7,desc:'Fully connected'},{n:'Softmax',t:'output',u:3,desc:'1000 classes'}],
   use_cases:['Image classification','Feature extraction','Style transfer'],pros:['Simple uniform design','Strong features'],cons:['138M params','Very slow']},
  {key:'efficientnet',icon:'◧',label:'EfficientNet',name:'EfficientNet-B0',cat:'Deep Learning',sub:'Vision',fw:['pytorch','tensorflow'],params:'5.3M',year:2019,
   desc:'Scales depth, width, and resolution uniformly using a compound coefficient. Achieves better accuracy with fewer parameters.',
   layers:[{n:'Stem Conv',t:'conv',u:4,desc:'3x3 conv'},{n:'MBConv1',t:'residual',u:5,desc:'Mobile inverted bottleneck'},{n:'MBConv6 x2',t:'residual',u:6,desc:'Expansion factor 6'},{n:'MBConv6 x2',t:'residual',u:6,desc:'Expansion factor 6'},{n:'MBConv6 x3',t:'residual',u:7,desc:'Expansion factor 6'},{n:'MBConv6 x3',t:'residual',u:7,desc:'Expansion factor 6'},{n:'MBConv6 x1',t:'residual',u:6,desc:'Expansion factor 6'},{n:'Head',t:'output',u:3,desc:'Classification'}],
   use_cases:['Mobile vision','Efficient classification'],pros:['High accuracy/param ratio','Scalable'],cons:['Complex architecture']},
  {key:'mobilenetv3',icon:'📱',label:'MobileNetV3',name:'MobileNetV3-Large',cat:'Deep Learning',sub:'Vision',fw:['pytorch','tensorflow'],params:'5.4M',year:2019,
   desc:'Hardware-aware network architecture search (NAS) combined with NetAdapt. Uses hard-swish and squeeze-and-excitation.',
   layers:[{n:'Conv2d',t:'conv',u:4,desc:'Standard conv'},{n:'Bneck x15',t:'residual',u:6,desc:'Inverted bottlenecks'},{n:'Conv2d',t:'conv',u:5,desc:'1x1 conv'},{n:'Pool',t:'pool',u:4,desc:'Avg pool'},{n:'Conv2d',t:'conv',u:4,desc:'1x1 conv'},{n:'Output',t:'output',u:3,desc:'Classification'}],
   use_cases:['On-device ML','Real-time vision'],pros:['Fast on mobile','Low latency'],cons:['Lower absolute accuracy']},
  {key:'inceptionv3',icon:'⎈',label:'InceptionV3',name:'Inception-v3',cat:'Deep Learning',sub:'Vision',fw:['pytorch','tensorflow'],params:'23.8M',year:2015,
   desc:'Uses Inception modules with factorized convolutions (e.g., 3x3 into 1x3 and 3x1) to reduce parameters while maintaining representational power.',
   layers:[{n:'Stem',t:'conv',u:5,desc:'Initial convs'},{n:'Inception A x3',t:'residual',u:6,desc:'35x35 grid'},{n:'Reduction A',t:'pool',u:5,desc:'Downsample'},{n:'Inception B x4',t:'residual',u:7,desc:'17x17 grid'},{n:'Reduction B',t:'pool',u:5,desc:'Downsample'},{n:'Inception C x2',t:'residual',u:6,desc:'8x8 grid'},{n:'GAP',t:'pool',u:4,desc:'Global pool'},{n:'Output',t:'output',u:3,desc:'Softmax'}],
   use_cases:['Image classification','Feature extraction'],pros:['Efficient parameter use','Multi-scale features'],cons:['Complex to implement']},
  {key:'densenet',icon:'⋈',label:'DenseNet-121',name:'Densely Connected CNN',cat:'Deep Learning',sub:'Vision',fw:['pytorch','tensorflow'],params:'8M',year:2017,
   desc:'Connects each layer to every other layer in a feed-forward fashion. Alleviates vanishing gradient and encourages feature reuse.',
   layers:[{n:'Conv',t:'conv',u:4,desc:'7x7 conv'},{n:'Pool',t:'pool',u:4,desc:'Max pool'},{n:'DenseBlock 1',t:'residual',u:6,desc:'6 layers'},{n:'Transition 1',t:'conv',u:5,desc:'Conv + Pool'},{n:'DenseBlock 2',t:'residual',u:7,desc:'12 layers'},{n:'Transition 2',t:'conv',u:5,desc:'Conv + Pool'},{n:'DenseBlock 3',t:'residual',u:8,desc:'24 layers'},{n:'Transition 3',t:'conv',u:5,desc:'Conv + Pool'},{n:'DenseBlock 4',t:'residual',u:6,desc:'16 layers'},{n:'Output',t:'output',u:3,desc:'Classification'}],
   use_cases:['Medical imaging','Image classification'],pros:['Feature reuse','Parameter efficient'],cons:['High memory usage during training']},
  {key:'vit',icon:'👁',label:'ViT',name:'Vision Transformer',cat:'Deep Learning',sub:'Vision',fw:['pytorch','jax'],params:'86M',year:2020,
   desc:'Applies a standard Transformer directly to images by splitting them into patches and treating them as a sequence of tokens.',
   layers:[{n:'Patch Embed',t:'embed',u:5,desc:'Image to patches'},{n:'Pos Embed',t:'embed',u:5,desc:'Learnable positions'},{n:'Transformer x12',t:'attention',u:7,desc:'Encoder blocks'},{n:'MLP Head',t:'output',u:4,desc:'Classification'}],
   use_cases:['Image classification','Transfer learning'],pros:['Scales well with data','Global context'],cons:['Needs massive data to train from scratch']},
  {key:'clip',icon:'🔗',label:'CLIP',name:'Contrastive Language-Image',cat:'Deep Learning',sub:'Multimodal',fw:['pytorch'],params:'150M',year:2021,
   desc:'Jointly trains an image encoder and text encoder to predict the correct pairings of a batch of (image, text) training examples.',
   layers:[{n:'Image Enc',t:'conv',u:6,desc:'ResNet or ViT'},{n:'Text Enc',t:'attention',u:6,desc:'Transformer'},{n:'Projection',t:'dense',u:5,desc:'To joint space'},{n:'Contrastive',t:'output',u:4,desc:'Cosine similarity'}],
   use_cases:['Zero-shot classification','Image search'],pros:['Zero-shot capabilities','Multimodal'],cons:['Requires massive paired datasets']},

  // Deep Learning › Attention / NLP
  {key:'transformer',icon:'⟡',label:'Transformer',name:'Transformer Encoder',cat:'Deep Learning',sub:'Attention',fw:['pytorch','tensorflow','jax','onnx'],params:'342K',year:2017,
   desc:'Self-attention computes pairwise token relationships enabling full-context parallel processing in O(n²·d). Foundation of modern LLMs.',
   layers:[{n:'Token Embed',t:'embed',u:5,desc:'Learned token embeddings'},{n:'Pos Encoding',t:'embed',u:5,desc:'Sinusoidal position info'},{n:'MH-Attention',t:'attention',u:5,desc:'8 heads × d_k=32'},{n:'Add & Norm',t:'norm',u:5,desc:'Residual + LayerNorm'},{n:'FFN (×4)',t:'dense',u:7,desc:'d_model → 4×d_model → d_model'},{n:'Add & Norm',t:'norm',u:5,desc:'Residual + LayerNorm'},{n:'CLS Pool',t:'pool',u:4,desc:'[CLS] token extraction'},{n:'Output',t:'output',u:4,desc:'Task head'}],
   use_cases:['NLP classification','Machine translation','Document understanding'],pros:['Full context attention','Parallelizable'],cons:['O(n²) attention','Large memory']},
  {key:'bert',icon:'⊞',label:'BERT',name:'Bidirectional Encoder Repr.',cat:'Deep Learning',sub:'Attention',fw:['pytorch','tensorflow','onnx'],params:'110M',year:2018,
   desc:'Pre-trained on MLM+NSP objectives with bidirectional context. Fine-tuning achieves SOTA on 11 NLP benchmarks with minimal architectural changes.',
   layers:[{n:'Token+Pos+Seg',t:'embed',u:5,desc:'3 embedding types summed'},{n:'Encoder ×12',t:'attention',u:6,desc:'12 transformer encoder layers'},{n:'Pooler (tanh)',t:'dense',u:4,desc:'[CLS] representation'},{n:'Task Head',t:'output',u:3,desc:'Classification/NER/QA'}],
   use_cases:['Text classification','NER','Question answering'],pros:['Bidirectional context','Strong fine-tuning'],cons:['110M params','Slow inference']},
  {key:'gpt',icon:'⊟',label:'GPT-2',name:'Autoregressive Transformer',cat:'Deep Learning',sub:'Attention',fw:['pytorch','tensorflow'],params:'117M',year:2019,
   desc:'Decoder-only causal transformer trained with next-token prediction. Causal masking ensures predictions depend only on previous tokens.',
   layers:[{n:'Token+Pos Emb',t:'embed',u:5,desc:'Learned embeddings'},{n:'Causal Attn ×12',t:'attention',u:6,desc:'Masked self-attention'},{n:'FFN ×12',t:'dense',u:6,desc:'MLP blocks'},{n:'LayerNorm',t:'norm',u:4,desc:'Pre-norm formulation'},{n:'LM Head',t:'output',u:5,desc:'Vocab logits'}],
   use_cases:['Text generation','Code completion','Summarization'],pros:['Few-shot learner','Open-ended generation'],cons:['Left-to-right only','No bidirectional']},
  {key:'t5',icon:'⇋',label:'T5',name:'Text-to-Text Transfer',cat:'Deep Learning',sub:'Attention',fw:['pytorch','tensorflow'],params:'220M',year:2019,
   desc:'Encoder-decoder transformer that frames all NLP tasks as text-to-text problems. Pre-trained with span corruption.',
   layers:[{n:'Embed',t:'embed',u:5,desc:'Token embeddings'},{n:'Encoder x12',t:'attention',u:6,desc:'Bidirectional'},{n:'Decoder x12',t:'attention',u:6,desc:'Causal + Cross-attn'},{n:'LM Head',t:'output',u:4,desc:'Vocab logits'}],
   use_cases:['Translation','Summarization','QA'],pros:['Unified framework','Strong performance'],cons:['Large model size']},
  {key:'roberta',icon:'⊞',label:'RoBERTa',name:'Robustly Optimized BERT',cat:'Deep Learning',sub:'Attention',fw:['pytorch','tensorflow'],params:'125M',year:2019,
   desc:'BERT variant trained longer, on more data, with larger batches, and dynamic masking. Removes NSP objective.',
   layers:[{n:'Embed',t:'embed',u:5,desc:'Token+Pos'},{n:'Encoder x12',t:'attention',u:6,desc:'Self-attention'},{n:'Task Head',t:'output',u:3,desc:'Classification'}],
   use_cases:['Text classification','NLI'],pros:['Better than BERT','Robust'],cons:['Computationally expensive']},

  // Deep Learning › Sequential
  {key:'lstm',icon:'↺',label:'LSTM',name:'Long Short-Term Memory',cat:'Deep Learning',sub:'Sequential',fw:['pytorch','tensorflow','jax','onnx'],params:'89K',year:1997,
   desc:'Four gates (input i, forget f, output o, cell g) control information flow through a persistent cell state C_t, enabling long-range temporal dependencies.',
   layers:[{n:'Embedding',t:'embed',u:4,desc:'Token → dense vector'},{n:'LSTM-128',t:'rnn',u:7,desc:'4 gates × 128 hidden'},{n:'LSTM-64',t:'rnn',u:5,desc:'Stacked recurrent layer'},{n:'Attention',t:'attention',u:5,desc:'Additive attention pooling'},{n:'Dense 64',t:'dense',u:4,desc:'Classification head'},{n:'Output',t:'output',u:3,desc:'Class probabilities'}],
   use_cases:['Sequence classification','Time series','NLP'],pros:['Long-range memory','Gated flow'],cons:['Sequential','Slow on long seqs']},
  {key:'gru',icon:'↻',label:'GRU',name:'Gated Recurrent Unit',cat:'Deep Learning',sub:'Sequential',fw:['pytorch','tensorflow','onnx'],params:'56K',year:2014,
   desc:'Simplified gating: reset r_t and update z_t gates replace LSTM\'s three gates. Fewer parameters with comparable performance on most sequence tasks.',
   layers:[{n:'Embedding',t:'embed',u:4,desc:'Token → dense vector'},{n:'GRU-128',t:'rnn',u:7,desc:'Reset + update gates'},{n:'GRU-64',t:'rnn',u:5,desc:'Stacked recurrent'},{n:'Dense 64',t:'dense',u:4,desc:'Task head'},{n:'Output',t:'output',u:3,desc:'Predictions'}],
   use_cases:['Time series','NLP','Music generation'],pros:['Fewer params than LSTM','Faster training'],cons:['Less expressive','Limited context']},
  {key:'bilstm',icon:'⇄',label:'BiLSTM',name:'Bidirectional LSTM',cat:'Deep Learning',sub:'Sequential',fw:['pytorch','tensorflow'],params:'178K',year:1997,
   desc:'Processes sequence in both forward and backward directions, concatenating the hidden states. Captures future context.',
   layers:[{n:'Embed',t:'embed',u:4,desc:'Tokens'},{n:'Forward LSTM',t:'rnn',u:6,desc:'L->R'},{n:'Backward LSTM',t:'rnn',u:6,desc:'R->L'},{n:'Concat',t:'dense',u:7,desc:'Merge states'},{n:'Output',t:'output',u:3,desc:'Task head'}],
   use_cases:['NER','POS tagging'],pros:['Bidirectional context'],cons:['Cannot be used for causal generation']},
  {key:'tcn',icon:'♒',label:'TCN',name:'Temporal ConvNet',cat:'Deep Learning',sub:'Sequential',fw:['pytorch','tensorflow'],params:'1.2M',year:2018,
   desc:'Uses 1D dilated causal convolutions to handle sequential data. Often outperforms RNNs with longer effective memory.',
   layers:[{n:'Input',t:'input',u:4,desc:'Sequence'},{n:'Dilated Conv 1',t:'conv',u:5,desc:'Dilation=1'},{n:'Dilated Conv 2',t:'conv',u:5,desc:'Dilation=2'},{n:'Dilated Conv 4',t:'conv',u:5,desc:'Dilation=4'},{n:'Output',t:'output',u:3,desc:'Prediction'}],
   use_cases:['Time series forecasting','Audio'],pros:['Parallelizable','Stable gradients'],cons:['Memory intensive during inference']},
  {key:'wavenet',icon:'🌊',label:'WaveNet',name:'WaveNet',cat:'Deep Learning',sub:'Sequential',fw:['pytorch','tensorflow'],params:'2M',year:2016,
   desc:'Deep generative model of raw audio waveforms using dilated causal convolutions. Autoregressive generation.',
   layers:[{n:'Causal Conv',t:'conv',u:4,desc:'Initial'},{n:'Dilated Block x10',t:'residual',u:6,desc:'Gated activation'},{n:'Skip Concat',t:'dense',u:5,desc:'Aggregate'},{n:'Softmax',t:'output',u:4,desc:'μ-law 256 classes'}],
   use_cases:['TTS','Audio generation'],pros:['High fidelity audio'],cons:['Very slow generation']},

  // Deep Learning › Generative
  {key:'vae',icon:'⊘',label:'VAE',name:'Variational Autoencoder',cat:'Deep Learning',sub:'Generative',fw:['pytorch','tensorflow','jax'],params:'1.4M',year:2013,
   desc:'ELBO = E[log p(x|z)] − KL(q(z|x)||p(z)). Reparameterization trick z=μ+σε enables backpropagation through stochastic latent variable.',
   layers:[{n:'Input',t:'input',u:6,desc:'Raw data'},{n:'Encoder',t:'dense',u:6,desc:'Inference network q(z|x)'},{n:'μ (mean)',t:'norm',u:3,desc:'Latent mean vector'},{n:'σ (std)',t:'norm',u:3,desc:'Latent std vector'},{n:'z ~ N(μ,σ)',t:'embed',u:3,desc:'Reparameterized sample'},{n:'Decoder',t:'dense',u:6,desc:'Generative network p(x|z)'},{n:'Reconstruct',t:'output',u:6,desc:'Reconstructed data'}],
   use_cases:['Generative modeling','Anomaly detection','Representation learning'],pros:['Structured latent space','Smooth interpolation'],cons:['Blurry outputs','Posterior collapse']},
  {key:'gan',icon:'⇋',label:'GAN',name:'Generative Adversarial Net.',cat:'Deep Learning',sub:'Generative',fw:['pytorch','tensorflow'],params:'2.1M',year:2014,
   desc:'Minimax game: G minimizes V(G,D) = E[log D(G(z))], D maximizes E[log D(x)]+E[log(1−D(G(z)))]. Mode collapse is primary challenge.',
   layers:[{n:'Noise z',t:'input',u:3,desc:'100-dim Gaussian noise'},{n:'G-Dense',t:'dense',u:5,desc:'Generator linear layers'},{n:'G-Upsample',t:'conv',u:7,desc:'Transposed convolutions'},{n:'G-Output',t:'output',u:5,desc:'Generated image (tanh)'},{n:'D-Conv',t:'conv',u:5,desc:'Discriminator features'},{n:'D-Dense',t:'dense',u:4,desc:'Classification layers'},{n:'Real/Fake',t:'output',u:3,desc:'Sigmoid probability'}],
   use_cases:['Image synthesis','Data augmentation','Style transfer'],pros:['Sharp samples','No explicit density'],cons:['Mode collapse','Training instability']},
  {key:'diffusion',icon:'≈',label:'Diffusion',name:'Denoising Diffusion Model',cat:'Deep Learning',sub:'Generative',fw:['pytorch','jax'],params:'860M',year:2020,
   desc:'Forward process: q(x_t|x_{t-1})=N(√(1-β_t)x_{t-1}, β_t I). Reverse: p_θ(x_{t-1}|x_t) learned via denoising score matching.',
   layers:[{n:'x_T (noise)',t:'input',u:4,desc:'Pure Gaussian noise'},{n:'Time Embed',t:'embed',u:4,desc:'Sinusoidal timestep t'},{n:'U-Net Down',t:'conv',u:7,desc:'Encoder with attention'},{n:'Bottleneck',t:'attention',u:6,desc:'Self-attention at 8×8'},{n:'U-Net Up',t:'conv',u:7,desc:'Decoder with skip connections'},{n:'x_0 predict',t:'output',u:4,desc:'Predicted clean image'}],
   use_cases:['Text-to-image','Inpainting','Audio generation'],pros:['SOTA quality','Stable training'],cons:['Very slow sampling','Huge compute']},

  // Deep Learning › Specialized
  {key:'unet',icon:'⋃',label:'U-Net',name:'U-Net Segmentation',cat:'Deep Learning',sub:'Specialized',fw:['pytorch','tensorflow','onnx'],params:'31M',year:2015,
   desc:'Symmetric encoder-decoder with skip connections at each resolution level. Skip connections preserve fine-grained spatial information lost during downsampling.',
   layers:[{n:'Input',t:'input',u:4,desc:'H×W×C image'},{n:'Enc1 (64)',t:'conv',u:5,desc:'Double conv, 64ch'},{n:'Enc2 (128)',t:'conv',u:6,desc:'Double conv, 128ch'},{n:'Enc3 (256)',t:'conv',u:7,desc:'Double conv, 256ch'},{n:'Bottleneck',t:'conv',u:7,desc:'512ch, deepest features'},{n:'Dec3+Skip',t:'conv',u:6,desc:'Upsample + concat skip'},{n:'Dec2+Skip',t:'conv',u:5,desc:'Upsample + concat skip'},{n:'Seg Mask',t:'output',u:4,desc:'Per-pixel class probs'}],
   use_cases:['Medical image segmentation','Satellite imagery','Cell detection'],pros:['Precise localization','Small data'],cons:['Memory intensive','Fixed input size']},
  {key:'siamese',icon:'⋈',label:'Siamese',name:'Siamese Network',cat:'Deep Learning',sub:'Specialized',fw:['pytorch','tensorflow'],params:'10M',year:1993,
   desc:'Twin networks with shared weights that learn a similarity metric between two inputs using contrastive or triplet loss.',
   layers:[{n:'Input 1',t:'input',u:3,desc:'Image A'},{n:'Input 2',t:'input',u:3,desc:'Image B'},{n:'Shared CNN',t:'conv',u:6,desc:'Feature extractor'},{n:'Distance',t:'dense',u:4,desc:'L1/L2 distance'},{n:'Output',t:'output',u:2,desc:'Similarity score'}],
   use_cases:['Face recognition','Signature verification'],pros:['Few-shot learning','Metric learning'],cons:['Sensitive to pair mining']},
  {key:'tabnet',icon:'▤',label:'TabNet',name:'TabNet',cat:'Deep Learning',sub:'Specialized',fw:['pytorch'],params:'1M',year:2019,
   desc:'Attentive transformer for tabular data. Uses sequential attention to choose which features to reason from at each decision step.',
   layers:[{n:'Input',t:'input',u:5,desc:'Tabular features'},{n:'Feature Trans.',t:'dense',u:6,desc:'Shared/Decision'},{n:'Attentive Trans.',t:'attention',u:5,desc:'Sparsemax mask'},{n:'Output',t:'output',u:3,desc:'Prediction'}],
   use_cases:['Tabular classification','Regression'],pros:['Interpretable','Handles unscaled data'],cons:['Can be slower than XGBoost']},
  {key:'deepfm',icon:'FM',label:'DeepFM',name:'Deep Factorization Machine',cat:'Deep Learning',sub:'Specialized',fw:['pytorch','tensorflow'],params:'5M',year:2017,
   desc:'Combines factorization machines for low-order feature interactions and deep neural networks for high-order interactions.',
   layers:[{n:'Sparse Input',t:'input',u:6,desc:'Categorical'},{n:'Embedding',t:'embed',u:5,desc:'Dense vectors'},{n:'FM Layer',t:'dense',u:4,desc:'Inner products'},{n:'DNN',t:'dense',u:6,desc:'MLP'},{n:'Output',t:'output',u:2,desc:'CTR prediction'}],
   use_cases:['Click-through rate','Recommender systems'],pros:['No manual feature engineering','End-to-end'],cons:['Requires large sparse datasets']},

  // Machine Learning › Linear
  {key:'linreg',icon:'⟋',label:'Linear Reg.',name:'Linear Regression',cat:'Machine Learning',sub:'Linear',fw:['sklearn'],params:'D+1',year:1805,viz:'regression',
   desc:'OLS minimizes ‖y−Xw‖². Closed-form: ŵ=(XᵀX)⁻¹Xᵀy. Gauss-Markov: BLUE under homoscedasticity and independence assumptions.',
   use_cases:['Trend analysis','Baseline model','Continuous prediction'],pros:['Interpretable','Closed-form','Fast'],cons:['Linear only','Sensitive to outliers','Multicollinearity']},
  {key:'logreg',icon:'⟋',label:'Logistic Reg.',name:'Logistic Regression',cat:'Machine Learning',sub:'Linear',fw:['sklearn'],params:'D+1',year:1958,viz:'svm',
   desc:'p(y=1|x)=σ(wᵀx+b). MLE via LBFGS or SGD. Probabilistic outputs. L1/L2/ElasticNet regularization variants available.',
   use_cases:['Binary classification','Probability calibration','Baseline'],pros:['Probabilistic output','Interpretable','Fast'],cons:['Linear boundary','Feature engineering needed']},
  {key:'ridge',icon:'⟋',label:'Ridge',name:'Ridge Regression (L2)',cat:'Machine Learning',sub:'Linear',fw:['sklearn'],params:'D+1',year:1970,viz:'regression',
   desc:'Adds λ‖w‖² to OLS loss. Closed-form: ŵ=(XᵀX+λI)⁻¹Xᵀy. Equivalent to MAP with Gaussian prior N(0,σ²/λ) on weights.',
   use_cases:['Multicollinear features','Regularized regression'],pros:['Stable with multicollinearity','Closed-form'],cons:['No feature selection','Linear only']},
  {key:'lasso',icon:'⟋',label:'Lasso',name:'Lasso Regression (L1)',cat:'Machine Learning',sub:'Linear',fw:['sklearn'],params:'D+1',year:1996,viz:'regression',
   desc:'Adds λ‖w‖₁ promoting exact sparsity via subdifferential conditions. Coordinate descent is most efficient solver for high-d settings.',
   use_cases:['Feature selection','Sparse regression','Genomics'],pros:['Automatic feature selection','Sparse'],cons:['Selects one from correlated group','Not differentiable at 0']},
  {key:'elasticnet',icon:'⟋',label:'ElasticNet',name:'Elastic Net Regression',cat:'Machine Learning',sub:'Linear',fw:['sklearn'],params:'D+1',year:2005,viz:'regression',
   desc:'Combines L1 and L2 penalties. Overcomes Lasso\'s limitation of selecting only one feature from a correlated group.',
   use_cases:['Highly correlated features','Sparse models'],pros:['Best of L1 and L2'],cons:['Two hyperparameters to tune']},

  // Machine Learning › Tree / Ensemble
  {key:'dtree',icon:'⊢',label:'Decision Tree',name:'Decision Tree',cat:'Machine Learning',sub:'Tree',fw:['sklearn'],params:'—',year:1984,viz:'tree',
   desc:'CART: greedy recursive partitioning choosing split (j,t) maximizing ΔGini or ΔEntropy. Fully grown trees overfit; pruning (cost-complexity) controls generalization.',
   use_cases:['Rule extraction','White-box classification','Feature importance'],pros:['Interpretable','No scaling','Handles mixed types'],cons:['Overfits easily','Unstable','Axis-aligned splits']},
  {key:'rf',icon:'⋐',label:'Random Forest',name:'Random Forest',cat:'Machine Learning',sub:'Ensemble',fw:['sklearn'],params:'—',year:2001,viz:'forest',
   desc:'Bagging of B trees, each trained on bootstrap sample with random feature subset m≈√d at each split. Variance reduction: Var(avg)=ρσ²+(1-ρ)σ²/B.',
   use_cases:['General classification','Feature importance','Regression'],pros:['Robust','OOB validation','Feature importance'],cons:['Not interpretable','Slow prediction']},
  {key:'xgb',icon:'⋒',label:'XGBoost',name:'Extreme Gradient Boosting',cat:'Machine Learning',sub:'Ensemble',fw:['xgboost','sklearn'],params:'—',year:2016,viz:'boost',
   desc:'Second-order Taylor expansion of loss + L1/L2 tree regularization. Column subsampling, histogram binning, and sparsity-aware split finding.',
   use_cases:['Kaggle competitions','Tabular data','Ranking'],pros:['SOTA tabular','Regularization','Sparse-aware'],cons:['Many hyperparams','Can overfit']},
  {key:'lgbm',icon:'⋒',label:'LightGBM',name:'Light Gradient Boosting',cat:'Machine Learning',sub:'Ensemble',fw:['lightgbm','sklearn'],params:'—',year:2017,viz:'boost',
   desc:'Leaf-wise (best-first) tree growth vs level-wise. Histogram binning reduces O(#data × #features) to O(#bin × #features). GOSS sub-samples low-gradient instances.',
   use_cases:['Large-scale tabular','Speed-critical tasks'],pros:['Very fast','Low memory','Native categorical'],cons:['Overfit on small data','Leaf-wise instability']},
  {key:'adaboost',icon:'⋒',label:'AdaBoost',name:'Adaptive Boosting',cat:'Machine Learning',sub:'Ensemble',fw:['sklearn'],params:'—',year:1995,viz:'boost',
   desc:'Weighted voting of T weak classifiers. Sample weight w_i updated: multiply by exp(α_t) for misclassified points. Final: H(x)=sign(Σα_t h_t(x)).',
   use_cases:['Face detection','Binary classification'],pros:['Interpretable boosting','No hyperparams tuning'],cons:['Sensitive to noise','Binary by default']},
  {key:'catboost',icon:'⋒',label:'CatBoost',name:'Categorical Gradient Boost',cat:'Machine Learning',sub:'Ensemble',fw:['lightgbm','sklearn'],params:'—',year:2017,viz:'boost',
   desc:'Ordered boosting via a permutation of training data prevents target leakage. Native categorical encoding with leave-one-out target statistics.',
   use_cases:['Categorical features','Financial data'],pros:['Native categorical','No leakage','Good defaults'],cons:['Slow training','GPU needed for large data']},
  {key:'gbm',icon:'⋒',label:'GBM',name:'Gradient Boosting Machine',cat:'Machine Learning',sub:'Ensemble',fw:['sklearn'],params:'—',year:2001,viz:'boost',
   desc:'Builds additive model in a forward stage-wise fashion. Fits regression trees to negative gradient of binomial/multinomial deviance loss.',
   use_cases:['Tabular classification','Regression'],pros:['High accuracy'],cons:['Sequential training','Prone to overfitting']},
  {key:'extratrees',icon:'⋐',label:'Extra Trees',name:'Extremely Randomized Trees',cat:'Machine Learning',sub:'Ensemble',fw:['sklearn'],params:'—',year:2006,viz:'forest',
   desc:'Like Random Forest, but uses the whole sample and chooses split points completely at random, further reducing variance.',
   use_cases:['High-variance datasets'],pros:['Faster than RF','Lower variance'],cons:['Higher bias than RF']},

  // Machine Learning › Kernel / Instance
  {key:'svm',icon:'⊕',label:'SVM (RBF)',name:'Support Vector Machine (RBF)',cat:'Machine Learning',sub:'Kernel',fw:['sklearn'],params:'—',year:1995,viz:'svm',
   desc:'Dual formulation: max Σα_i − ½ΣΣα_i α_j y_i y_j K(x_i,x_j). KKT conditions: only support vectors (α_i>0) define the hyperplane.',
   use_cases:['High-dim classification','Text','Bioinformatics'],pros:['Effective in high-dim','Kernel trick','Margin maximization'],cons:['O(n³) training','Kernel choice tricky']},
  {key:'svm_linear',icon:'⊕',label:'SVM (Linear)',name:'Linear SVM',cat:'Machine Learning',sub:'Kernel',fw:['sklearn'],params:'—',year:1995,viz:'svm',
   desc:'Linear kernel SVM. Faster to train than RBF, suitable for linearly separable or very high dimensional data (like text).',
   use_cases:['Text classification'],pros:['Fast','Interpretable weights'],cons:['Linear boundary only']},
  {key:'knn',icon:'⊛',label:'KNN',name:'K-Nearest Neighbors',cat:'Machine Learning',sub:'Instance',fw:['sklearn'],params:'—',year:1951,viz:'knn',
   desc:'No training phase. At inference: find k nearest neighbors by L_p distance; classify by plurality vote. k-d tree or ball tree accelerates search to O(log n).',
   use_cases:['Recommendation','Anomaly detection','Imputation'],pros:['No training','Multi-class natural','Interpretable'],cons:['O(n·d) per query','Memory: stores all data','Scale-sensitive']},

  // Machine Learning › Probabilistic
  {key:'nb',icon:'⊞',label:'Gaussian NB',name:'Gaussian Naive Bayes',cat:'Machine Learning',sub:'Probabilistic',fw:['sklearn'],params:'—',year:1960,viz:'svm',
   desc:'P(y|x)∝P(y)·∏P(x_i|y). Gaussian: P(x_i|y)=N(x_i;μ_iy,σ²_iy). Zero-frequency problem solved by Laplace/add-k smoothing.',
   use_cases:['Text classification','Spam detection'],pros:['Very fast','Works on small data','Probabilistic'],cons:['Independence assumption','Calibration issues']},
  {key:'multinb',icon:'⊞',label:'Multinomial NB',name:'Multinomial Naive Bayes',cat:'Machine Learning',sub:'Probabilistic',fw:['sklearn'],params:'—',year:1960,viz:'svm',
   desc:'Naive Bayes for multinomially distributed data. Classic algorithm for text classification with word counts or tf-idf.',
   use_cases:['Document classification'],pros:['Fast','Good baseline for text'],cons:['Independence assumption']},

  // Machine Learning › Clustering
  {key:'kmeans',icon:'✦',label:'K-Means',name:'K-Means Clustering',cat:'Machine Learning',sub:'Clustering',fw:['sklearn'],params:'—',year:1967,viz:'kmeans',
   desc:'Lloyd\'s algorithm alternates assignment and M-step: μ_k = (1/|C_k|)Σx_i. k-means++ initialization: sample proportional to D(x)² for better convergence.',
   use_cases:['Market segmentation','Image compression'],pros:['Fast','Simple','Scalable'],cons:['K must be specified','Spherical assumption','Outlier sensitive']},
  {key:'dbscan',icon:'◉',label:'DBSCAN',name:'Density-Based Clustering',cat:'Machine Learning',sub:'Clustering',fw:['sklearn'],params:'—',year:1996,viz:'dbscan',
   desc:'Core point: ≥minPts neighbors within ε. Border point reachable from core. Noise: not reachable. Handles arbitrary shapes and marks outliers natively.',
   use_cases:['Geospatial clustering','Anomaly detection'],pros:['No K needed','Arbitrary shapes','Noise handling'],cons:['ε sensitive','Poor on varying density']},
  {key:'gmm',icon:'◎',label:'GMM',name:'Gaussian Mixture Model',cat:'Machine Learning',sub:'Clustering',fw:['sklearn'],params:'—',year:1977,viz:'gmm',
   desc:'EM: E-step computes posterior r_ik=p(z=k|x_i); M-step updates π_k,μ_k,Σ_k. BIC/AIC used for selecting number of components K.',
   use_cases:['Soft clustering','Density estimation'],pros:['Soft assignments','Flexible shape','Probabilistic'],cons:['K must be specified','EM local optima']},
  {key:'agglo',icon:'⋈',label:'Agglomerative',name:'Agglomerative Clustering',cat:'Machine Learning',sub:'Clustering',fw:['sklearn'],params:'—',year:1963,viz:'dendrogram',
   desc:'Bottom-up hierarchical clustering. Merges pairs of clusters based on linkage criteria (Ward, complete, average, single).',
   use_cases:['Taxonomy creation'],pros:['Outputs dendrogram','No K needed initially'],cons:['O(n³) time complexity']},
  {key:'spectral',icon:'∿',label:'Spectral',name:'Spectral Clustering',cat:'Machine Learning',sub:'Clustering',fw:['sklearn'],params:'—',year:2000,viz:'kmeans',
   desc:'Uses top eigenvectors of a graph Laplacian matrix to embed data into a lower-dimensional space before applying K-Means.',
   use_cases:['Non-convex clusters'],pros:['Handles complex geometries'],cons:['Expensive eigenvalue computation']},

  // Machine Learning › Dim. Reduction
  {key:'pca',icon:'↗',label:'PCA',name:'Principal Component Analysis',cat:'Machine Learning',sub:'Dim. Reduction',fw:['sklearn'],params:'—',year:1901,viz:'embedding',
   desc:'SVD of centered data matrix: X=UΣVᵀ. Principal components V[:,0:k] maximize variance. Explained variance ratio: λ_i/Σλ_j.',
   use_cases:['Dimensionality reduction','Visualization','Noise removal'],pros:['Fast','Interpretable','Optimal linear reduction'],cons:['Linear only','Loses information']},
  {key:'tsne',icon:'≀',label:'t-SNE',name:'t-Distributed Stochastic Emb.',cat:'Machine Learning',sub:'Dim. Reduction',fw:['sklearn'],params:'—',year:2008,viz:'embedding',
   desc:'Minimizes KL(P||Q) where p_ij∝exp(-‖x_i-x_j‖²/2σ²), q_ij∝(1+‖y_i-y_j‖²)⁻¹. Barnes-Hut approximation reduces O(n²) to O(n log n).',
   use_cases:['High-dim visualization','Cluster exploration'],pros:['Excellent visualization','Preserves local structure'],cons:['Non-deterministic','Slow for large n']},
  {key:'umap',icon:'∪',label:'UMAP',name:'Uniform Manifold Approx.',cat:'Machine Learning',sub:'Dim. Reduction',fw:['sklearn'],params:'—',year:2018,viz:'embedding',
   desc:'Constructs a high-dimensional graph representation of the data then optimizes a low-dimensional graph to be structurally similar.',
   use_cases:['Visualization','Pre-processing'],pros:['Faster than t-SNE','Preserves global structure'],cons:['Requires tuning']},
  {key:'ica',icon:'↹',label:'ICA',name:'Independent Component Analysis',cat:'Machine Learning',sub:'Dim. Reduction',fw:['sklearn'],params:'—',year:1986,viz:'embedding',
   desc:'Separates a multivariate signal into additive, independent non-Gaussian components. Maximizes statistical independence.',
   use_cases:['Blind source separation','EEG/MEG analysis'],pros:['Finds independent sources'],cons:['Assumes non-Gaussianity']},
  {key:'lda',icon:'↘',label:'LDA',name:'Linear Discriminant Analysis',cat:'Machine Learning',sub:'Dim. Reduction',fw:['sklearn'],params:'—',year:1936,viz:'embedding',
   desc:'Supervised dimensionality reduction. Maximizes class separability by maximizing between-class variance and minimizing within-class variance.',
   use_cases:['Feature extraction for classification'],pros:['Supervised','Fast'],cons:['Assumes Gaussian distribution']},

  // Machine Learning › Anomaly Detection
  {key:'isoforest',icon:'⋐',label:'Isolation Forest',name:'Isolation Forest',cat:'Machine Learning',sub:'Anomaly',fw:['sklearn'],params:'—',year:2008,viz:'forest',
   desc:'Anomalies are isolated in fewer random splits than inliers. Anomaly score: s(x,n)=2^{-E[h(x)]/c(n)} where c(n)=2H(n-1)-(2(n-1)/n).',
   use_cases:['Fraud detection','Network intrusion'],pros:['Linear time','Memory efficient','No distance metric'],cons:['Binary output','Threshold tuning']},
  {key:'oneclass',icon:'⊕',label:'One-Class SVM',name:'One-Class SVM',cat:'Machine Learning',sub:'Anomaly',fw:['sklearn'],params:'—',year:1999,viz:'svm',
   desc:'Separates data from origin in kernel feature space: min ½‖w‖²−ρ+1/νn·Σξ_i. Decision boundary: f(x)=sign(w·Φ(x)−ρ).',
   use_cases:['Novelty detection','Network security'],pros:['Single-class training','Kernel flexibility'],cons:['Slow on large data','ν hard to interpret']},
  {key:'lof',icon:'⊛',label:'LOF',name:'Local Outlier Factor',cat:'Machine Learning',sub:'Anomaly',fw:['sklearn'],params:'—',year:2000,viz:'knn',
   desc:'LOF_k(p)=(1/|N_k(p)|)·Σ_{o∈N_k(p)} lrd_k(o)/lrd_k(p). lrd: local reachability density. LOF>1 indicates sparser neighborhood than peers.',
   use_cases:['Network intrusion','Medical outliers'],pros:['Local density awareness','Varying densities'],cons:['High LOF ≠ anomaly','Slow on large datasets']},
];
